# Home Page

/:
  controller: Home
  action: index

/home:
  controller: Home
  action: index

# Register

/register:
  controller: Register
  action: index

/register/submit:
  controller: Register
  action: register

# Login

/login:
  controller: Login
  action: index

/login/submit:
  controller: Login
  action: login

# Logout

/logout:
  controller: LogoutController
  action: index

#Delete

/delete-account:
  controller: DeleteAccountController
  action: deleteAccount

/delete-account-success:
  controller: DeleteAccountController
  action : deleteSuccess
  
# User 

/account:
  controller: UserAccountController
  action: index

# Vérification d'email

/verify-email:
  controller: EmailVerificationController
  action: index

# Dashboard Admin

/admin/dashboard:
  controller: AdminController
  action: dashboard

/admin/logs:
  controller: AdminController
  action: logs

/admin/users:
  controller: AdminController
  action: index

# Bibliothèque

library:
  controller: LibraryController
  action: index

library/add:
  controller: LibraryController
  action: addBook

library/book/{id}:
  controller: LibraryController
  action: viewBook

library/book/{id}/add-review:
  controller: LibraryController
  action: addReview

library/delete/{id}:
  controller: LibraryController
  action: deleteBook
